// Generated by ReScript, PLEASE EDIT WITH CARE


var ary = [
  1,
  2
];

var msgs = [
  "jus",
  "testing"
];

var test = msgs.join(" ");

var tup = [
  1,
  2
];

export {
  tup ,
  ary ,
  test ,
  
}
/* test Not a pure module */
